site_name: Seeing is...
repo_url: https://github.com/elissasoroj/seeingis
site_author: Elissa Sorojsrisom
#to deploy: mkdocs gh-deploy --force
#to see dummy site: mkdocs serve

# Copyright
copyright: Copyright &copy; 2022 Elissa Sorojsrisom

nav:
  - Welcome: index.md
  - About: 
    - about.md
    #- index.md
    #- How to Use: index.md
  - Visual Literacy:
    - Visual Literacy & Visual Thinking: vlvt.md
    #- Visual Communication in Science: science.md
    #- Visuals for Teaching: teaching.md
  - Crash Course: 
    - course/intro.md
    #- Vectors & File Types: vectors.md
    - Amuse-Bouche:
      - Shape Tools: course/shape.md
      - Pathfinder: course/pathfinder.md
      - Project: course/shape-proj.md
    - Main Course:
      - Pen Tool: course/main.md
      #- Pen Tool Thinking: thinking.md
      #- Pen Tool Exercises: exercises.md
      #- Walkthrough: walkthrough.md
  - Workshop: Art of the Science Graphic: 
    - workshop.md
    - 1. Purpose: workshop/coming-soon.md #purpose.md
    - 2. Concept: workshop/coming-soon.md #concept.md
    - 3. Sketch: workshop/coming-soon.md #sketch.md
    - 4. Reflect: workshop/coming-soon.md #reflect.md
    - 5. Adjust: workshop/coming-soon.md #adjust.md
    - 6. Reference: workshop/coming-soon.md #reference.md
    - 7. Create: workshop/coming-soon.md #create.md
    - 8. Evaluate: workshop/coming-soon.md #evaluate.md
    - 9. Review: workshop/coming-soon.md #review.md
  #- Gallery: gallery.md
  #- Glossary: index.md

edit_uri: ""

theme:
  name: material
  palette:
    - scheme: seeingis-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: yellow
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    #text: Quicksand
  icon:
    logo: octicons/codespaces-24
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/cpu-16
      success: octicons/check-16
      question: octicons/unverified-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes

#extra - Google Analytics
extra:
  analytics:
    provider: google
    property: G-VPWFQJYN0F
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: octicons/thumbsup-16
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback! If you have any additional suggestions
            please consider filling out 
            our <a href="https://forms.gle/Y8xi6ga5rKcGtzEg9">feedback form</a>.
        - icon: octicons/thumbsdown-16
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/Y8xi6ga5rKcGtzEg9">feedback form</a>.

#Python Markdown Extentions
markdown_extensions:
  - toc:
      toc_depth: 4
  - markdown.extensions.codehilite:
      guess_lang: false      
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html  
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

#Javascript Extentions
extra_javascript:
  - javascripts/feedback.js
  # - js/custom.js 
  # - https://unpkg.com/mermaid@8.9.2/dist/mermaid.min.js
  # - https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.0.9/mermaid.min.js
  # - js/termynal.js
  # - js/mermaid.js

extra_css:
  - stylesheets/extra.css